// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_DcxvfuHFz_mI2whrKuVouE9vffcgCiE',
    appId: '1:698309262764:web:eaf932e37903a3fd058e09',
    messagingSenderId: '698309262764',
    projectId: 'flutter-mobilegame',
    authDomain: 'flutter-mobilegame.firebaseapp.com',
    databaseURL: 'https://flutter-mobilegame-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-mobilegame.appspot.com',
    measurementId: 'G-DPGC17VHMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdZ9KdexC8NdbpwAyNAbNm6JmoSJYwYNg',
    appId: '1:698309262764:android:4c834dbb00c26527058e09',
    messagingSenderId: '698309262764',
    projectId: 'flutter-mobilegame',
    databaseURL: 'https://flutter-mobilegame-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-mobilegame.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzqG1QLUcPiwXU-HIImLWxl4M1aucH1vM',
    appId: '1:698309262764:ios:4c623e2f17953fef058e09',
    messagingSenderId: '698309262764',
    projectId: 'flutter-mobilegame',
    databaseURL: 'https://flutter-mobilegame-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-mobilegame.appspot.com',
    iosClientId: '698309262764-8tvml4u1rn4pdv7oe64o33s2s16omjkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilegame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzqG1QLUcPiwXU-HIImLWxl4M1aucH1vM',
    appId: '1:698309262764:ios:4c623e2f17953fef058e09',
    messagingSenderId: '698309262764',
    projectId: 'flutter-mobilegame',
    databaseURL: 'https://flutter-mobilegame-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-mobilegame.appspot.com',
    iosClientId: '698309262764-8tvml4u1rn4pdv7oe64o33s2s16omjkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilegame',
  );
}
